<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260216110538 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE audit_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(255) NOT NULL, ip_address VARCHAR(45) DEFAULT NULL, user_agent VARCHAR(500) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, performed_by_id INT DEFAULT NULL, vault_id INT DEFAULT NULL, secret_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F6E1C0F52E65C292 ON audit_log (performed_by_id)');
        $this->addSql('CREATE INDEX IDX_F6E1C0F558AC2DF8 ON audit_log (vault_id)');
        $this->addSql('CREATE INDEX IDX_F6E1C0F567176C07 ON audit_log (secret_id)');
        $this->addSql('CREATE TABLE secret (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, encrypted_value VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_accessed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, vault_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5CA2E8E558AC2DF8 ON secret (vault_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, two_factor_secret VARCHAR(255) DEFAULT NULL, two_factor_enabled BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE vault (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FF3049217E3C61F9 ON vault (owner_id)');
        $this->addSql('CREATE TABLE vault_member (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, vault_id INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B76ECA0058AC2DF8 ON vault_member (vault_id)');
        $this->addSql('CREATE INDEX IDX_B76ECA00F675F31B ON vault_member (author_id)');
        $this->addSql('ALTER TABLE audit_log ADD CONSTRAINT FK_F6E1C0F52E65C292 FOREIGN KEY (performed_by_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE audit_log ADD CONSTRAINT FK_F6E1C0F558AC2DF8 FOREIGN KEY (vault_id) REFERENCES vault (id)');
        $this->addSql('ALTER TABLE audit_log ADD CONSTRAINT FK_F6E1C0F567176C07 FOREIGN KEY (secret_id) REFERENCES secret (id)');
        $this->addSql('ALTER TABLE secret ADD CONSTRAINT FK_5CA2E8E558AC2DF8 FOREIGN KEY (vault_id) REFERENCES vault (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vault ADD CONSTRAINT FK_FF3049217E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vault_member ADD CONSTRAINT FK_B76ECA0058AC2DF8 FOREIGN KEY (vault_id) REFERENCES vault (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vault_member ADD CONSTRAINT FK_B76ECA00F675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE audit_log DROP CONSTRAINT FK_F6E1C0F52E65C292');
        $this->addSql('ALTER TABLE audit_log DROP CONSTRAINT FK_F6E1C0F558AC2DF8');
        $this->addSql('ALTER TABLE audit_log DROP CONSTRAINT FK_F6E1C0F567176C07');
        $this->addSql('ALTER TABLE secret DROP CONSTRAINT FK_5CA2E8E558AC2DF8');
        $this->addSql('ALTER TABLE vault DROP CONSTRAINT FK_FF3049217E3C61F9');
        $this->addSql('ALTER TABLE vault_member DROP CONSTRAINT FK_B76ECA0058AC2DF8');
        $this->addSql('ALTER TABLE vault_member DROP CONSTRAINT FK_B76ECA00F675F31B');
        $this->addSql('DROP TABLE audit_log');
        $this->addSql('DROP TABLE secret');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE vault');
        $this->addSql('DROP TABLE vault_member');
    }
}
